FROM alpine:edge
WORKDIR /spotdl
RUN apk add --no-cache python3 py3-pip
RUN python3 -m venv /temp-pymodule/ && . /temp-pymodule/bin/activate
RUN pip install spotdl
RUN spotdl --download-ffmpeg
RUN deactivate
COPY songs.txt ./
RUN spotdl $(cat songs.txt)
CMD [ "pwd && ls"]
